<?php
    require_once '../src/BootstrapTwitter/Autoloader.php';

    $button = new \BootstrapTwitter\UI\Button();
    echo $button;
    echo $button->setValue('Primary Button')->setColorType('primary');
    echo $button->setValue('Primary Button')->setColorType('info');
    echo $button->setValue('Primary Button')->setColorType('success');
    echo $button->setValue('Primary Button')->setColorType('danger');
?>